module.exports = {
  APP_SECRET: 'jsaksdasidpaoqpi91208j',
  HUBSPOT_CONSTANTS: {
    INITIAL_ID_DISTRITO: 5000,
    END_POINT: 'http://api.hubapi.com/',
    API_KEY: '2c17b627-0c76-4182-b31a-6874e67d32b3',
    API_PATH_ACTION:
            {
              CREATE_DEAL: 'deals/v1/deal',
              UPDATE_DEAL: 'deals/v1/deal/',
              CREATE_CONTACT: 'contacts/v1/contact',
              GET_CONTACT: 'contacts/v1/contact/email/',
            },
            PIPELINE:                       `${process.env.PIPELINE_HUB}`,  //'a5b260cb-3992-4766-b669-20d07735c6f8'
            DEAL_STAGES:{
                REGISTER:                    `${process.env.DATE_HUB}`,   // Development: 366828
                REQUEST_IN_PROCESS:          `${process.env.DATE_HUB}`,   // 88b229ab-5161-4c94-ab74-fd68faee5140 SolicitudCUrsoREgistro parciasl
                INTEGRATING_DOCUMENTATION:   `${process.env.DATE_HUB}`,   // d52c3e71-74ee-499b-8af9-abe5245deaaa Integrando documentacion p
                BURO_CALL:                   `${process.env.DATE_HUB}`,   // d0874266-3f5f-44a4-9905-76f9e1871805 LLmara PAra P
                NO_MINIMUM_REQUIREMENTS:     `${process.env.DATE_HUB}`,   // ebdea2f6-dea7-4646-b8e0-089a4b7f5c02 Rechazado
            },
    OWNER_ID: '36264467',
    DEAL_PROPERTIES: {
      ID_DISTRITO: 'numeroderegistro',
      COMERCIAL_NAME: 'nombre_comercial',
      EMAIL: 'email',
      CELLPHONE: 'telefono',
      DEAL_NAME: 'dealname',
      PERSON_TYPE: 'tipo_de_persona',
      AMOUNT: 'amount',
      PAY_TIME: 'n2_2_tiempo_para_pago',
      WHY_NEED: 'necesidad_de_financiamiento',
      WHEN_NEED: 'n2_4_urgencia_de_financiamiento',
      YEAR_SALES: 'n2_5_ventas_anuales',
      BUSSINES_AGE: 'n2_6_antig_edad_del_negocio',
      COMERCIAL_NAME: 'n3_nombre_comercial',
      SPIN: 'giro',
      SPECIFIC_ACTIVITY: 'n3_actividad_espec_fica',
      RFC: 'n3_rfc',
      STREET: 'n3_calle',
      ETX_NUM: 'n3_num_ext',
      INT_NUM: 'n3_num_int',
      ZIP_CODE: 'codigo_postal',
      TOWN: 'n3_9_colonia',
      PHONE: 'telefono',
      WEB_SITE: 'n3_11_sitio_web',
      FACEBOOK: 'n3_12_facebook',
      TPV: 'n3_13_tpv',
      GARANTIA: 'n3_14_garant_a',
      CIEC: 'n4_93_ciec',
      GENERALPHONE: 'n4_92_tel_fono',
      SCORE: 'calificacion_cliente',
      BIRTH_DATE: 'n4_5_fecha_de_nacimiento',
      CAR_CREDIT: 'n6_2_cr_dito_automotriz',
      CIVIL_STATUS: 'n4_4_estado_civil',
      CREDIT_CARD: 'n6_3_tarjeta_de_cr_dito',
      LAST4: 'n6_4_tdc_4_d_gitos',
      LASTNAME: 'n4_2_apellido_paterno',
      MORTAGAGE_CREDIT: 'n6_1_cr_dito_hipotecario',
      NAME: 'n4_1_nombre',
      SECOND_LASNAME: 'n4_3_apellido_materno',
      REFERENCE_NAME: 'n5_1_nombre_referencia',
      REFERENCE_PHONE: 'n5_2_tel_fono_referencia',
      REFERENCE_PARENTESCO: 'n5_3_parentesco_referencia',
      PROOFADDRESS: 'n9_2_comp_domicilio',
      BANKSTATEMENTS: 'n9_3_estados_de_cuenta',
    },
    FULL_DEAL_PROPERTIES: {
      oficialID: ['n9_1_id',
        'n9_1_2_id',
        'n9_1_3_id',
        'n9_1_4_id',
      ],
      proofAddress: ['n9_2_comp_domicilio',
        'n9_2_1_comp_domicilio_2',
        'n9_2_2_comp_domicilio_3',
      ],
      bankStatements: ['n9_3_estados_de_cuenta',
        'n9_3_1_estados_de_cuenta',
        'n9_3_2_estados_de_cuenta',
        'n9_3_3_estados_de_cuenta',
        'n9_3_4_estados_de_cuenta',
        'n9_3_5_estados_de_cuenta',
        'n9_3_6_estados_de_cuenta',
        'n9_3_7_estados_de_cuenta',
        'n9_3_8_estados_de_cuenta',
        'n9_3_9_estados_de_cuenta',
        'n9_3_10_estados_de_cuenta',
        'n9_3_11_estados_de_cuenta',
      ],
      rfc: ['n9_4_rfc'],
      lastDeclarations: ['n9_5_declaraci_n',
        'n9_5_1_declaraci_n',
        'n9_5_2_declaraci_n',
        'n9_5_3_declaraci_n',
      ],
      acomplishOpinion: ['n9_6_opini_n_de_cumplimiento'],
      constitutiveAct: ['n9_9_acta_constitutiva'],
      otherActs: [''],
      financialStatements: ['n9_93_1_eeff',
        'n9_93_1_1_eeff',
        'n9_93_2_eeff',
        'n9_93_2_1_eeff',
        'n9_93_3_eeff',
        'n9_93_3_1_eeff',
      ],
      others: ['n9_8_otros',
        'n9_8_1_otros_2',
        'n9_8_2_otros_3',
        'n9_8_3_otros_4',
      ],
    },
    ENUMS: {
      PERSON_TYPE: {
        MORAL: 'Persona Moral',
        P_FISICA_EMPRESARIAL: 'Persona Física con A.E.',
        RIF: 'RIF',
        P_FISICA: 'Persona Física',
      },
    },
  },
  SENDGRID: {
    API_KEY: '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',
  },
};
